spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    keyspace-name: test_keyspace
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra
    request:
      timeout: 5s
    connection:
      connect-timeout: 10s