server:
  servlet:
    context-path: /dwhs
  port: 4000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: dwhs_keyspace
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    request:
      timeout: 5s
    connection:
      connect-timeout: 10s